#! /bin/bash
# generated by collect_git_remote_add_recursively.sh

pushd $(dirname $0)                                                             2> /dev/null   > /dev/null
cd ..

mode="d"
debug=

if test $# -eq 0 ; then
  mode="h"
fi

while getopts ":fDqh" opt ; do
#echo opt+arg = "$opt$OPTARG"
case "$opt$OPTARG" in
f )
  echo "--- check out master/HEAD before registering all git remotes ---"
  mode="f"
  ;;

D )
  debug="T"
  ;;

"?" )
  echo "--- set up git remotes only ---"
  ;;

q )
  echo "--- set up git remotes only ---"
  mode="q"
  ;;

* )
  mode="h"
  ;;
esac
done

# chop off the commandline parameters parsed above, i.e. keep the user-specified paths
for (( i=OPTIND; i > 1; i-- )) do
  shift
done

if [ $debug ] ; then echo "mode=$mode, debug=$debug, [$#] --> [$@]" ; fi

if test $mode = "h" ; then
  cat <<EOT
$0 [-f] [-F] [-D] [-q] [submodule-paths]

set up git remotes for any / all submodules.

-f       : 'full featured', i.e. refresh all submodule remotes: change their access URIs
           when they have changed.
-D       : DEBUG: print extensive debug / progress information.           
-q       : 'quick', i.e. only register all submodule remotes which have not been
           set up yet.

Default behaviour is 'quick mode'.

submodule-paths
         : when you specify one or more submodule directories, than only the
           remotes for those submodules will be set up.
           This is optional; the default sets up the remotes for ALL submodules.
	   Specify '.' as the path to match ALL submodules.

EOT
  exit
fi

submodule=xxxxxx

# args: (path, name, repo, argc, argv...)
function register_remote {
    argc=$#
    argv=("$@")
    path=$1
    name=$2
    repo=$3
    if [ $debug ] ; then echo "register_remote [$path] [$name] [$repo] [$argc] [...]"; fi
    #if [ $debug ] ; then echo "--> register_remote [$@]"; fi

    # only when paths have been specified on the commandline do we check whether the given remote should be registered
    # (apart from the separate check to see if the submodule has actually been installed, see further below)
    if test $argc -gt 4 ; then
        hit=0
        for ((i=4; i < $argc; i++)); do
            #echo testing dir $i: ${argv[$i]}
            if test ${argv[$i]} = $path ; then
                hit=1
                break
            fi
        done
    else
        hit=1
    fi

    if [ $debug ] ; then echo "TEST HIT = $hit --> $( test $hit -ne 0 ; echo $? )" ; fi
    if test $hit -ne 0 ; then
        if [ $debug ] ; then echo "PATH = $path --> $( test -d $path ; echo $? ), $( test -e $path/.git ; echo $? )"; fi
        if test -d $path && test -e $path/.git ; then
            if [ $debug ] ; then echo "ACTION! (mode = $mode)"; fi
            if test $submodule != $path ; then
                echo -------------------------------------------------------------------------------------
                echo submodule:: $path
                submodule=$path
            fi
            pushd $path                                                         2> /dev/null   > /dev/null
            if test "$mode" = "f" ; then
		if [ $debug ] ; then echo "git remote rm $name"; fi
                git remote rm $name
            fi
            if [ $debug ] ; then echo "git remote add $name $repo"; fi
            git remote add $name $repo
            popd                                                                2> /dev/null   > /dev/null
        fi
    fi
}






register_remote .                                                             0xsirsaif                                https://github.com/GerHobbelt/sqlite.git                                         $# $@
register_remote .                                                             1101642336                               https://github.com/1101642336/sqlite.git                                         $# $@
register_remote .                                                             adsharma                                 https://github.com/adsharma/sqlite.git                                           $# $@
register_remote .                                                             aglv                                     https://github.com/aglv/sqlite.git                                               $# $@
register_remote .                                                             ahgamut                                  https://github.com/ahgamut/sqlite.git                                            $# $@
register_remote .                                                             alagoutte                                https://github.com/alagoutte/sqlite.git                                          $# $@
register_remote .                                                             alpinejoe                                https://github.com/alpinejoe/sqlite.git                                          $# $@
register_remote .                                                             AlvarHHM                                 https://github.com/AlvarHHM/sqlite.git                                           $# $@
register_remote .                                                             ApacheSourceCode                         https://github.com/ApacheSourceCode/sqlite.git                                   $# $@
register_remote .                                                             ar-visions                               https://github.com/ar-visions/sqlite.git                                         $# $@
register_remote .                                                             b41sh                                    https://github.com/b41sh/sqlite.git                                              $# $@
register_remote .                                                             bnnk                                     https://github.com/bnnk/sqlite.git                                               $# $@
register_remote .                                                             bukinr                                   https://github.com/bukinr/sqlite.git                                             $# $@
register_remote .                                                             Chaz6                                    https://github.com/Chaz6/sqlite.git                                              $# $@
register_remote .                                                             check-spelling                           https://github.com/check-spelling/sqlite.git                                     $# $@
register_remote .                                                             chenpy-a                                 https://github.com/chenpy-a/sqlite.git                                           $# $@
register_remote .                                                             chkob                                    https://github.com/chkob/sqlite.git                                              $# $@
register_remote .                                                             chuanglun                                https://github.com/chuanglun/sqlite.git                                          $# $@
register_remote .                                                             clin1234                                 https://github.com/clin1234/sqlite.git                                           $# $@
register_remote .                                                             coconan                                  https://github.com/coconan/sqlite.git                                            $# $@
register_remote .                                                             colinking                                https://github.com/colinking/sqlite.git                                          $# $@
register_remote .                                                             crossbuild                               https://github.com/crossbuild/sqlite.git                                         $# $@
register_remote .                                                             CTSRD-CHERI                              https://github.com/CTSRD-CHERI/sqlite.git                                        $# $@
register_remote .                                                             czj831143                                https://github.com/czj831143/sqlite.git                                          $# $@
register_remote .                                                             d3x0r                                    https://github.com/d3x0r/sqlite.git                                              $# $@
register_remote .                                                             databaseleague                           https://github.com/databaseleague/sqlite.git                                     $# $@
register_remote .                                                             dcou                                     https://github.com/dcou/sqlite.git                                               $# $@
register_remote .                                                             dna2fork                                 https://github.com/dna2fork/sqlite.git                                           $# $@
register_remote .                                                             engomarwasfy                             https://github.com/engomarwasfy/sqlite.git                                       $# $@
register_remote .                                                             flawk                                    https://github.com/flawk/sqlite.git                                              $# $@
register_remote .                                                             freedge                                  https://github.com/freedge/sqlite.git                                            $# $@
register_remote .                                                             ftes                                     https://github.com/ftes/sqlite.git                                               $# $@
register_remote .                                                             G-P-S                                    https://github.com/G-P-S/sqlite-mirror.git                                       $# $@
register_remote .                                                             Gac14                                    https://github.com/Gac14/sqlite.git                                              $# $@
register_remote .                                                             garci66                                  https://github.com/garci66/sqlite.git                                            $# $@
register_remote .                                                             GerHobbelt                               https://github.com/GerHobbelt/sqlite.git                                         $# $@
register_remote .                                                             Gerhobbelt                               https://github.com/Gerhobbelt/sqlite.git                                         $# $@
register_remote .                                                             httpsgithu                               https://github.com/httpsgithu/sqlite.git                                         $# $@
register_remote .                                                             ihnesto                                  https://github.com/ihnesto/sqlite.git                                            $# $@
register_remote .                                                             ikingye                                  https://github.com/ikingye/sqlite.git                                            $# $@
register_remote .                                                             isanych                                  https://github.com/isanych/sqlite.git                                            $# $@
register_remote .                                                             jaocekeo                                 https://github.com/jaocekeo/sqlite.git                                           $# $@
register_remote .                                                             JerryHue                                 https://github.com/JerryHue/sqlite.git                                           $# $@
register_remote .                                                             jfzhang2                                 https://github.com/jfzhang2/sqlite.git                                           $# $@
register_remote .                                                             jinyyu                                   https://github.com/jinyyu/sqlite.git                                             $# $@
register_remote .                                                             jjhenkel                                 https://github.com/jjhenkel/sqlite.git                                           $# $@
register_remote .                                                             jssmith                                  https://github.com/jssmith/sqlite.git                                            $# $@
register_remote .                                                             Keikai1880                               https://github.com/Keikai1880/sqlite.git                                         $# $@
register_remote .                                                             klassenjs                                https://github.com/klassenjs/sqlite-antacid.git                                  $# $@
register_remote .                                                             knizhnik                                 https://github.com/knizhnik/sqlite.git                                           $# $@
register_remote .                                                             kurtbuilds                               https://github.com/kurtbuilds/sqlite.git                                         $# $@
register_remote .                                                             Lekensteyn                               https://github.com/Lekensteyn/sqlite.git                                         $# $@
register_remote .                                                             liuluheng                                https://github.com/liuluheng/sqlite.git                                          $# $@
register_remote .                                                             lstefano71                               https://github.com/lstefano71/sqlite.git                                         $# $@
register_remote .                                                             luluandleilei                            https://github.com/luluandleilei/sqlite.git                                      $# $@
register_remote .                                                             luzpaz                                   https://github.com/luzpaz/sqlite.git                                             $# $@
register_remote .                                                             mackyle                                  https://github.com/mackyle/sqlite.git                                            $# $@
register_remote .                                                             mackyle-original                         https://github.com/mackyle/sqlite.git                                            $# $@
register_remote .                                                             Malterlib                                https://github.com/Malterlib/sqlite.git                                          $# $@
register_remote .                                                             mandel59                                 https://github.com/mandel59/sqlite.git                                           $# $@
register_remote .                                                             masayuki2009                             https://github.com/masayuki2009/sqlite.git                                       $# $@
register_remote .                                                             mengjiahao                               https://github.com/mengjiahao/sqlite.git                                         $# $@
register_remote .                                                             mingodad                                 https://github.com/mingodad/sqlite.git                                           $# $@
register_remote .                                                             mitsutaka-takeda                         https://github.com/mitsutaka-takeda/sqlite.git                                   $# $@
register_remote .                                                             mp-lee                                   https://github.com/mp-lee/sqlite.git                                             $# $@
register_remote .                                                             MrMage                                   https://github.com/MrMage/sqlite.git                                             $# $@
register_remote .                                                             msdx321                                  https://github.com/msdx321/sqlite.git                                            $# $@
register_remote .                                                             msorvig                                  https://github.com/msorvig/sqlite-hacks.git                                      $# $@
register_remote .                                                             mtippett                                 https://github.com/mtippett/sqlite.git                                           $# $@
register_remote .                                                             mturk                                    https://github.com/mturk/sqlite.git                                              $# $@
register_remote .                                                             Mu-L                                     https://github.com/Mu-L/sqlite.git                                               $# $@
register_remote .                                                             neonkingfr                               https://github.com/neonkingfr/sqlite.git                                         $# $@
register_remote .                                                             ng-alt                                   https://github.com/ng-alt/sqlite.git                                             $# $@
register_remote .                                                             nikoandpiko                              https://github.com/nikoandpiko/sqlite.git                                        $# $@
register_remote .                                                             outtersg                                 https://github.com/outtersg/sqlite.git                                           $# $@
register_remote .                                                             Pandinosaurus                            https://github.com/Pandinosaurus/sqlite.git                                      $# $@
register_remote .                                                             pbartruff                                https://github.com/pbartruff/sqlite.git                                          $# $@
register_remote .                                                             peterpuhov-github                        https://github.com/peterpuhov-github/sqlite.git                                  $# $@
register_remote .                                                             pkhuong                                  https://github.com/pkhuong/sqlite.git                                            $# $@
register_remote .                                                             Pranay144                                https://github.com/Pranay144/sqlite.git                                          $# $@
register_remote .                                                             pspdev                                   https://github.com/pspdev/sqlite.git                                             $# $@
register_remote .                                                             pwnall                                   https://github.com/pwnall/sqlite.git                                             $# $@
register_remote .                                                             R-fred                                   https://github.com/R-fred/sqlite.git                                             $# $@
register_remote .                                                             raindust                                 https://github.com/raindust/sqlite.git                                           $# $@
register_remote .                                                             repo-cz                                  https://repo.or.cz/sqlite.git                                                    $# $@
register_remote .                                                             returntocorp-hackathon                   https://github.com/returntocorp-hackathon/sqlite.git                             $# $@
register_remote .                                                             Rosonix                                  https://github.com/Rosonix/cc-sqlite.git                                         $# $@
register_remote .                                                             Rostov1991                               https://github.com/Rostov1991/sqlite.git                                         $# $@
register_remote .                                                             rsalmaso                                 https://github.com/rsalmaso/sqlite.git                                           $# $@
register_remote .                                                             ruomeng0x                                https://github.com/ruomeng0x/sqlite.git                                          $# $@
register_remote .                                                             rurban                                   https://github.com/rurban/hardsqlite.git                                         $# $@
register_remote .                                                             SandeepVaman                             https://github.com/SandeepVaman/sqlite.git                                       $# $@
register_remote .                                                             satoridev01                              https://github.com/satoridev01/test.sqlite.sqlite.git                            $# $@
register_remote .                                                             shamrin                                  https://github.com/shamrin/sqlite-1.git                                          $# $@
register_remote .                                                             Single-Cell-Technologies                 https://github.com/Single-Cell-Technologies/sqlite.git                           $# $@
register_remote .                                                             sqlite                                   https://github.com/sqlite/sqlite.git                                             $# $@
register_remote .                                                             sqlite-original                          https://github.com/GerHobbelt/sqlite.git                                         $# $@
register_remote .                                                             sthagen                                  https://github.com/sthagen/sqlite-sqlite.git                                     $# $@
register_remote .                                                             ternava                                  https://github.com/ternava/sqlite.git                                            $# $@
register_remote .                                                             TiagoSilva777                            https://github.com/TiagoSilva777/sqlite.git                                      $# $@
register_remote .                                                             trafi                                    https://github.com/trafi/sqlite.git                                              $# $@
register_remote .                                                             val-verde                                https://github.com/val-verde/sqlite.git                                          $# $@
register_remote .                                                             waltarix                                 https://github.com/waltarix/sqlite.git                                           $# $@
register_remote .                                                             willoughbyrm                             https://github.com/willoughbyrm/sqlite.git                                       $# $@
register_remote .                                                             wjz1029                                  https://github.com/wjz1029/sqlite.git                                            $# $@
register_remote .                                                             WyattJia                                 https://github.com/WyattJia/sqlite.git                                           $# $@
register_remote .                                                             xiaodezhang                              https://github.com/xiaodezhang/sqlite.git                                        $# $@
register_remote .                                                             XinYao1994                               https://github.com/XinYao1994/sqlite.git                                         $# $@
register_remote .                                                             xudong963                                https://github.com/xudong963/sqlite-annotation.git                               $# $@
register_remote .                                                             yaowagn                                  https://github.com/yaowagn/sqlite.git                                            $# $@
register_remote .                                                             yet                                      https://github.com/yet/sqlite.git                                                $# $@
register_remote .                                                             yurydelendik                             https://github.com/yurydelendik/sqlite.git                                       $# $@
register_remote .                                                             zavla                                    https://github.com/zavla/sqlite.git                                              $# $@
register_remote .                                                             zhangtb                                  https://github.com/zhangtb/sqlite.git                                            $# $@
register_remote .                                                             zzir                                     https://github.com/zzir/sqlite.git                                               $# $@



popd                                                                            2> /dev/null   > /dev/null

